### PR TITLE
docs(static-site-generator): migrate from mkdocs to docusaurus

### PR DESCRIPTION
**Pull request by adnanrahic**
This PR migrates the docs from mkdocs to docusaurus.

The content is a carbon copy, only the static-site generator and theme have been changed.

Would be great to get some 👀 on this to make sure I covered all the bases.

Demo of the new docs: https://ornate-faun-1ceac5.netlify.app/

## Changes

- `docs` folder has been changed to Docusaurus
- removed all mkdocs files
- added GH action workflow for Docusaurus

## Fixes

- N/A

## Checklist

- [x] tested locally
- [x] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by adnanrahic** [comment]
Team, let's **not** merge this until we have the green light from Ken and Julianne. 👌

**Comment by mathnogueira** [comment]
The only thing that should be double-checked is if docusaurus is capable of rendering the mermaid diagrams and emojis correctly on the website.

### diagrams:
Screenshot from 2022-11-21 16-24-37

### emojis:
Screenshot from 2022-11-21 16-25-36

Both can be found at https://docs.tracetest.io/advanced-selectors/

**Comment by adnanrahic** [comment]
Yep, there's a plugin for it which I enabled.
ornate-faun-1ceac5 netlify app_concepts_advanced-selectors

**Review by mathnogueira — APPROVED** [review]
Great job!

**Pull request merged**
