### PR TITLE
feat: http server with custom prefix

### PR DESCRIPTION
**Pull request by greut**
This PR... is a work in progress. Any help is much appreciated.

TODO:

- [ ] Figure out how to inject `<base href="/">` into the page, and rewrite the JS path to be relative to that

## Changes

- Allows to configure the HTTP server, host, port, and prefix

## Fixes

- Expose `tracetest` on a particular prefix, the routing will be done by Traefik.

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by schoren** [comment]
Hey @greut, thank you very much for your contribution. We'd like to understand what you are trying to achieve with this. I get that you want tracetest to live under a customisable path.
Could you provide some examples on the kind of deployment you are looking for?

**Comment by schoren** [comment]
Got it. Seems like a useful setting , plus I like having the HTTP settings configurable. I think it would be great to have an integration test covering this thogh.
Also, this setting will impact the fronted too.

We're working on figuring out how to test this setting so it doesn't break anything

**Comment by schoren** [comment]
@cescoferraro @jorgeepc do you know how hard would it be to make the web UI work on a subdomain?

**Comment by cescoferraro** [comment]
@schoren it depends on the approach we are taking. 
You need a way to run the frontend image setting the public path via an env variable?

**Comment by mathnogueira** [comment]
Hey @greut! This definitely would be a cool feature for tracetest. About integration testing, I experimented in a different branch (#701) how we could write an integration test for that feature. I created this branch to test it, you might want to take a look to see how we are testing stuff.

About injecting things on the HTML, we use a template file for that, you could modify it to create a `<base href="{{ .ServerPathPrefix }}">` there. We are doing that with Google Analytics stuff [here](https://github.com/kubeshop/tracetest/blob/main/web/public/index.html#L29) and [here](https://github.com/kubeshop/tracetest/blob/597f239c52ed9db1d1bdd031a567e6e266718837/server/app/app.go#L114)

**Comment by jorgeepc** [comment]
@greut @schoren @mathnogueira to serve the UI I think we have different options. Of course we need to solve it at runtime and not build time. We could try something like this:
- Convert `static assets` paths to relative paths in the `index.html` file by setting `"homepage": "."` in our `package.json`. And then probably change the way we [serve them from the server](https://github.com/kubeshop/tracetest/blob/597f239c52ed9db1d1bdd031a567e6e266718837/server/app/app.go#L59) and adjust our [web router](https://github.com/kubeshop/tracetest/blob/main/web/src/components/Navigation/Router.tsx#L8).

**Comment by jorgeepc** [comment]
@greut @schoren @mathnogueira to serve the UI I think we have different options. Of course we need to solve it at runtime and not build time. We could try something like this:
- Convert `static assets` paths to relative paths in the `index.html` file by setting `"homepage": "."` in our `package.json`. And then probably change the way we [serve them from the server](https://github.com/kubeshop/tracetest/blob/597f239c52ed9db1d1bdd031a567e6e266718837/server/app/app.go#L59) and adjust our [web router](https://github.com/kubeshop/tracetest/blob/main/web/src/components/Navigation/Router.tsx#L8).

**Comment by greut** [comment]
> About injecting things on the HTML, we use a template file for that, you could modify it to create a `<base href="{{ .ServerPathPrefix }}">` there. We are doing that with Google Analytics stuff [here](https://github.com/kubeshop/tracetest/blob/main/web/public/index.html#L29) and [here](https://github.com/kubeshop/tracetest/blob/597f239c52ed9db1d1bdd031a567e6e266718837/server/app/app.go#L114).

I saw that bit and didn't find where the css/js where injected into that page. `%PUBLIC_URL%` could be a candidate to be changed via the `tplVars`.

**Comment by mathnogueira** [comment]
> I saw that bit and didn't find where the css/js where injected into that page.

I'm not 100% sure, but it seems that they are injected during build time. @jorgeepc can you confirm that?

> %PUBLIC_URL% could be a candidate to be changed via the tplVars.

My understanding is that %PUBLIC_URL% is replaced during the web app build, so adding it on the backend will not have any effect. You would have to build another docker image with a specific path prefix for that to work.

I think that the best approach would be using a `<base>` tag for that. You would need to change [this const](https://github.com/kubeshop/tracetest/blob/main/web/src/redux/apis/TraceTest.api.ts#L13) to start using `document.baseURI` as part of the PATH.

**Comment by jorgeepc** [comment]
@mathnogueira @greut 
Yes, `js` and `css` are injected during build time. And `PUBLIC_URL` is also replaced during build time.

**Comment by mathnogueira** [comment]
Hey @greut . I tried understand what would be necessary to enable this feature and figured this is a complex feature that requires changes in multiple parts of tracetest. So, I updated my PR to update everything we would need to do to enable this feature. You can take a look at the implementation on the PR #701. As soon as it gets merged, I'll notify you.

**Comment by greut** [comment]
@mathnogueira it was my feelings as well, thanks a lot for the hard work!

**Comment by greut** [comment]
@mathnogueira it's working perfectly! :tada:

**Comment by mathnogueira** [comment]
Awesome to hear that @greut! Let us know if you miss a feature you'd like to see in future versions of Tracetest. We really want feedback from people that are using it, and it would be awesome if we could chat sometime about what you want to achieve with Tracetest and hear your feedback about it. Could we set a meeting up to hear your feedback about the project?

**Pull request closed without merging**
