### PR TITLE
feat(frontend): Resizable Panels for the Test run

### PR DESCRIPTION
**Pull request by xoscar**
This PR updates the style of the resizable panels for the test run tabs, allowing users to drag the panels to their choice depending on what they want to focus on

## Changes

- Adds resizable logic for trigger, test and automate

## Fixes

-  https://github.com/kubeshop/tracetest/issues/3665

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Loom video

https://www.loom.com/share/788dc005396f4a13aadff3e549bf8021

### CODE REVIEW

**Comment by olha23** [comment]
@xoscar I like everything related to behaviour included how you made minimal width for resizable sections. But regarding visual styles - i would ask you to leave our current one. In your version, these elements attract a lot of attention on the page, but this is just a secondary functionality that should improve the user's work when necessary. 
- the open/close function we already doing though our toggle-drawer
- the full size panel option user will make by dragging the panel on left or right

**Comment by olha23** [comment]
and examples for automate tab:
Frame 60770
Frame 60771

**Review by jorgeepc — COMMENTED** [review]
Hey @xoscar great job! The code looks good to me. I have a couple of comments:

- I see a `web/src/components/RunDetailAutomate/TechniquesPanel.tsx` empty file. Should we delete it?
- Did you validate that the resize functionality works correct with the virtual list? We have a virtual list in the test specs. Let's double check that is working as expected.
- I'm not a big fan of the new UI header to close/open the panels. Let's work with @olha23 in a proposal for that.

Screenshot 2024-02-28 at 10 12 56

**Comment by xoscar** [comment]
@olha23 @jorgeepc new vid
https://www.loom.com/share/f2df2f0d917b48e8a7d2447f85f364d8

**Comment by olha23** [comment]
@xoscar looks great, thanks!

**Review by jorgeepc — APPROVED** [review]
Looks good my friend! 🔥

**Pull request merged**
