### PR TITLE
fix: use old proto image if amd64 arch

### PR DESCRIPTION
**Pull request by mathnogueira**
This PR enables people using AMD64 architecture to generate our protobuf code.

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by mathnogueira** [comment]
@schoren can you check if that breaks your M1 environment?

**Comment by schoren** [comment]
@mathnogueira I don't have internet at home until friday, so I'm using my laptop, which isn't m1. I can test it then. Why do you need to do this change?

**Comment by mathnogueira** [comment]
> @mathnogueira I don't have internet at home until friday, so I'm using my laptop, which isn't m1. I can test it then. Why do you need to do this change?

No problem. We can approve that later. I added this PR because I'm not using an M1 laptop, so when I try to run: `make`, I get this error:

```
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
make: *** [Makefile:77: proto] Error 1
```

Applying the changes of this PR, it doesn't fail.

**Comment by schoren** [comment]
Mhh, I think I can make the docker image cross platform. Let me try to fix it that way

**Comment by mathnogueira** [comment]
This fix works on the M1 chip as well. Thanks @cescoferraro 

image

**Review by schoren — APPROVED** [review]

**Pull request merged**
