### PR TITLE
add query to test detail page

### PR DESCRIPTION
**Pull request by cescoferraro**
This PR adds search capabilities to the test detail page which shows a list of test runs for a given test

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by cescoferraro** [comment]
@kdhamric @schoren this is working, but I am not sure what would the search be based upon.
The run entity does not have much information in it for us to query. We can always `inner-join` the test entity. But then it would match all of the runs always. What should the query look for in this case

**Comment by kdhamric** [comment]
Yes - searching is not very helpful here. Filtering, however, is useful. Show me the test runs with or without failures. Select test runs by a date range.  

The spot where searching may be valuable is in searching against the fields captured by #1066 - being able to quickly find the test run associated with a particular PR, etc will be helpful.

I would, however, question putting much work into this capability yet, particularly if we need backend team involvement. Bigger fish to fry that will impact initial engagement with the product.

**Comment by cescoferraro** [comment]
@kdhamric the backend part is done as well. if we need #1066 fields to be able to filter the results, we need to wait for it.
I can close this one now, but when they exist, we can just reopen this because the code is the same. Just need to change the SQL script

**Comment by kdhamric** [comment]
Lets come back to it once the #1066 is done. Normally I would say to put what you have in there... but I literally cannot think of one thing that would be useful to search for.  Can it handle any kind of filtering - on date ranges or passed/failed tests?

**Comment by cescoferraro** [comment]
@kdhamric we can add the filtering!

**Pull request closed without merging**
