### PR TITLE
docs: Undefined Variables Documentation

### PR DESCRIPTION
**Pull request by jfermi**
Added undefined-variables.md and updated the navigation.

This PR...

## Changes

-

## Fixes

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [x] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by jfermi** [comment]
> GJ @jfermi do you mind adding more complex scenarios like having variables within assertions and possibly a transaction with more than one test? 😬 thanks!

**Comment by adnanrahic** [comment]
> GJ @jfermi do you mind adding more complex scenarios like having variables within assertions and possibly a transaction with more than one test? 😬 thanks!

@xoscar Can you provide short bullet points that would help us write this more complex scenario?

**Comment by jfermi** [comment]
I don't think I am the best person to do this. Oscar, could you run through
this process and send me the screen shots? I will add to the documentation.

**Comment by olha23** [comment]
@jfermi i will add screen shots

**Comment by olha23** [comment]
@jfermi here is the screen shots:
Screenshot 2023-01-11 at 2 04 31 PM
Screenshot 2023-01-11 at 1 59 22 PM
Screenshot 2023-01-11 at 1 57 00 PM
Screenshot 2023-01-11 at 2 08 01 PM
Screenshot 2023-01-11 at 2 08 34 PM
Screenshot 2023-01-11 at 1 58 00 PM


@xoscar can you please check also

**Comment by jfermi** [comment]
Thank you!

**Review by kdhamric — APPROVED** [review]
Looks good!

**Review by mathnogueira — APPROVED** [review]

**Pull request merged**
