### PR TITLE
🔗 1086 adding deep-linking feature

### PR DESCRIPTION
**Pull request by xoscar**
This PR adds the base logic to support deep linking across the application. It includes a single-way data flow where components update the URL query by using an action. Which is then listened by a redux middleware which triggers the side effect actions based on the URL change.

## Changes

- Component no longer update the selected span or assertion directly.

## Fixes

- https://github.com/kubeshop/tracetest/issues/1052
- https://github.com/kubeshop/tracetest/issues/1086

## Checklist

- [x] tested locally
- [x] added new dependencies
- [ ] updated the docs
- [x] added a test

https://www.loom.com/share/121648cb912248be9bd4f67b1ed31c0a

### CODE REVIEW

**Comment by cescoferraro** [comment]
@xoscar  Code looks good at first glance. Thank you! One thing I noticed on your demo, is that we are passing the selector to the url. I get that we need this because the assertion's id is it's selector. But can we mask this, let's say by hashing it someway, so users wont notice that?

**Comment by xoscar** [comment]
> @xoscar Code looks good at first glance. Thank you! One thing I noticed on your demo, is that we are passing the selector to the url. I get that we need this because the assertion's id is it's selector. But can we mask this, let's say by hashing it someway, so users wont notice that?

Great idea, I'll work on that!

**Comment by xoscar** [comment]
Hey @jorgeepc & @cescoferraro this one should be ready for the final review

**Review by cescoferraro — APPROVED** [review]
LGTM

**Pull request merged**
